name: ci

on:
  pull_request:
    branches: [ master ]

jobs:
  quality-assurance:
    name: Quality Assurance API
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Установка UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.14'

      - name: QA
        run: make full_qa